from __future__ import annotations

from typing import Any


NODE_TYPES: list[dict[str, Any]] = [
    {
        "type": "manual_trigger",
        "label": "Manual Trigger",
        "category": "trigger",
        "icon": "▶",
        "description": "Start a workflow manually.",
        "executor": "manual_trigger",
        "inputs": [],
        "outputs": [{"id": "next", "label": "Next"}],
        "configSchema": [],
    },
    {
        "type": "webhook_trigger",
        "label": "Webhook Trigger",
        "category": "trigger",
        "icon": "↪",
        "description": "Start from an inbound webhook.",
        "executor": "webhook_trigger",
        "inputs": [],
        "outputs": [{"id": "next", "label": "Next"}],
        "configSchema": [{"key": "path", "label": "Webhook path", "type": "string", "required": True, "default": "/webhook/alos_current"}],
    },
    {
        "type": "schedule_trigger",
        "label": "Schedule Trigger",
        "category": "trigger",
        "icon": "◷",
        "description": "Start on a schedule.",
        "executor": "schedule_trigger",
        "inputs": [],
        "outputs": [{"id": "next", "label": "Next"}],
        "configSchema": [{"key": "schedule", "label": "Schedule", "type": "string", "required": True, "default": "hourly"}],
    },
    {
        "type": "rexhub_event_trigger",
        "label": "ALOSHub Event Trigger",
        "category": "trigger",
        "icon": "◆",
        "description": "Start when a ALOSHub event arrives.",
        "executor": "rexhub_event_trigger",
        "inputs": [],
        "outputs": [{"id": "next", "label": "Next"}],
        "configSchema": [{"key": "eventType", "label": "Event type", "type": "string", "required": True, "default": "task.created"}],
    },
    {
        "type": "http_request",
        "label": "HTTP Request",
        "category": "integration",
        "icon": "⌁",
        "description": "Call an HTTP endpoint from the backend.",
        "executor": "http_request",
        "inputs": [{"id": "in", "label": "In"}],
        "outputs": [{"id": "next", "label": "Next"}],
        "configSchema": [
            {"key": "method", "label": "Method", "type": "select", "required": True, "default": "GET", "options": ["GET", "POST", "PUT", "PATCH", "DELETE"]},
            {"key": "url", "label": "URL", "type": "string", "required": True, "default": "https://example.com"},
            {"key": "headersJson", "label": "Headers JSON", "type": "text", "required": False, "default": "{}"},
            {"key": "body", "label": "Body", "type": "text", "required": False, "default": ""},
            {"key": "timeoutSeconds", "label": "Timeout seconds", "type": "number", "required": True, "default": 10},
        ],
    },
    {
        "type": "transform_data",
        "label": "Transform Data",
        "category": "action",
        "icon": "ƒ",
        "description": "Apply a deterministic transform expression.",
        "executor": "transform_data",
        "inputs": [{"id": "in", "label": "In"}],
        "outputs": [{"id": "next", "label": "Next"}],
        "configSchema": [{"key": "expression", "label": "Expression", "type": "text", "required": False, "default": "return input"}],
    },
    {
        "type": "condition",
        "label": "Condition",
        "category": "flow",
        "icon": "?",
        "description": "Branch based on a condition.",
        "executor": "condition",
        "inputs": [{"id": "in", "label": "In"}],
        "outputs": [{"id": "true", "label": "True"}, {"id": "false", "label": "False"}],
        "configSchema": [{"key": "condition", "label": "Condition", "type": "string", "required": True, "default": "true"}],
    },
    {
        "type": "parallel_branch",
        "label": "Parallel Branch",
        "category": "flow",
        "icon": "∥",
        "description": "Start multiple branches.",
        "executor": "parallel_branch",
        "inputs": [{"id": "in", "label": "In"}],
        "outputs": [{"id": "a", "label": "A"}, {"id": "b", "label": "B"}],
        "configSchema": [],
    },
    {
        "type": "join",
        "label": "Join",
        "category": "flow",
        "icon": "⋈",
        "description": "Join branches after parallel work.",
        "executor": "join",
        "inputs": [{"id": "in", "label": "In"}],
        "outputs": [{"id": "next", "label": "Next"}],
        "configSchema": [],
    },
    {
        "type": "delay",
        "label": "Delay",
        "category": "flow",
        "icon": "⏱",
        "description": "Wait before continuing.",
        "executor": "delay",
        "inputs": [{"id": "in", "label": "In"}],
        "outputs": [{"id": "next", "label": "Next"}],
        "configSchema": [{"key": "seconds", "label": "Seconds", "type": "number", "required": True, "default": 1}],
    },
    {
        "type": "approval_gate",
        "label": "Approval Gate",
        "category": "swarm",
        "icon": "✓",
        "description": "Pause for human or Department Head approval.",
        "executor": "approval_gate",
        "inputs": [{"id": "in", "label": "In"}],
        "outputs": [{"id": "approved", "label": "Approved"}, {"id": "rejected", "label": "Rejected"}],
        "configSchema": [
            {"key": "assigneeId", "label": "Approver", "type": "string", "required": True, "default": "dh_operations"},
            {"key": "authorityTier", "label": "Authority tier", "type": "number", "required": True, "default": 1},
        ],
    },
    {
        "type": "create_task",
        "label": "Create Task",
        "category": "task",
        "icon": "□",
        "description": "Create a workflow-linked task.",
        "executor": "create_task",
        "inputs": [{"id": "in", "label": "In"}],
        "outputs": [{"id": "next", "label": "Next"}],
        "configSchema": [
            {"key": "title", "label": "Title", "type": "string", "required": True, "default": "Review workflow output"},
            {"key": "priority", "label": "Priority", "type": "select", "required": True, "default": "normal", "options": ["low", "normal", "high", "urgent"]},
        ],
    },
    {
        "type": "assign_department_head",
        "label": "Assign Department Head",
        "category": "swarm",
        "icon": "DH",
        "description": "Assign work to a Department Head.",
        "executor": "assign_department_head",
        "inputs": [{"id": "in", "label": "In"}],
        "outputs": [{"id": "next", "label": "Next"}],
        "configSchema": [{"key": "departmentId", "label": "Department", "type": "string", "required": True, "default": "operations"}],
    },
    {
        "type": "assign_sub_agent",
        "label": "Assign Sub-Agent",
        "category": "swarm",
        "icon": "SA",
        "description": "Assign work to a capable sub-agent.",
        "executor": "assign_sub_agent",
        "inputs": [{"id": "in", "label": "In"}],
        "outputs": [{"id": "next", "label": "Next"}],
        "configSchema": [{"key": "capability", "label": "Capability", "type": "string", "required": True, "default": "research"}],
    },
    {
        "type": "swarm_assignment",
        "label": "Swarm Assignment",
        "category": "swarm",
        "icon": "⚙",
        "description": "Manually select an agent or define a capability for autonomous routing.",
        "executor": "swarm_assignment",
        "inputs": [{"id": "in", "label": "In"}],
        "outputs": [{"id": "next", "label": "Next"}],
        "configSchema": [
            {"key": "assignmentMode", "label": "Assignment mode", "type": "select", "required": True, "default": "autonomous", "options": ["manual", "autonomous"]},
            {"key": "agentId", "label": "Agent ID (Manual)", "type": "agent_select", "required": False, "default": ""},
            {"key": "capability", "label": "Capability (Autonomous)", "type": "string", "required": False, "default": "research"},
        ],
    },
    {
        "type": "escalation_gate",
        "label": "Escalation Gate",
        "category": "swarm",
        "icon": "!",
        "description": "Escalate when revision or risk limits are reached.",
        "executor": "escalation_gate",
        "inputs": [{"id": "in", "label": "In"}],
        "outputs": [{"id": "next", "label": "Next"}],
        "configSchema": [{"key": "maxRevisions", "label": "Max revisions", "type": "number", "required": True, "default": 3}],
    },
    {
        "type": "notification",
        "label": "Notification",
        "category": "action",
        "icon": "✉",
        "description": "Emit a notification event.",
        "executor": "notification",
        "inputs": [{"id": "in", "label": "In"}],
        "outputs": [{"id": "next", "label": "Next"}],
        "configSchema": [{"key": "message", "label": "Message", "type": "text", "required": True, "default": "Workflow update"}],
    },
    {
        "type": "audit_log",
        "label": "Audit Log",
        "category": "action",
        "icon": "≡",
        "description": "Write an audit event.",
        "executor": "audit_log",
        "inputs": [{"id": "in", "label": "In"}],
        "outputs": [{"id": "next", "label": "Next"}],
        "configSchema": [{"key": "message", "label": "Message", "type": "text", "required": True, "default": "Audit checkpoint"}],
    },
    {
        "type": "output",
        "label": "Output",
        "category": "output",
        "icon": "◉",
        "description": "Complete a workflow branch.",
        "executor": "output",
        "inputs": [{"id": "in", "label": "In"}],
        "outputs": [],
        "configSchema": [{"key": "summary", "label": "Summary", "type": "text", "required": False, "default": "Done"}],
    },
    {
        "type": "shell",
        "label": "Run Shell Command",
        "category": "action",
        "icon": "🐚",
        "description": "Execute a shell command inside an observed PTY environment.",
        "executor": "shell",
        "inputs": [{"id": "in", "label": "In"}],
        "outputs": [{"id": "next", "label": "Next"}],
        "configSchema": [
            {"key": "command", "label": "Command", "type": "text", "required": True, "default": "echo 'Hello ALOS'"},
            {"key": "timeoutSeconds", "label": "Timeout seconds", "type": "number", "required": True, "default": 60},
        ],
    },
    {
        "type": "invoke_agent",
        "label": "Invoke Agent",
        "category": "swarm",
        "icon": "A",
        "description": "Invoke a LangGraph agent swarm turn (RFC-0002).",
        "executor": "invoke_agent",
        "inputs": [{"id": "in", "label": "In"}],
        "outputs": [{"id": "next", "label": "Next"}],
        "configSchema": [
            {"key": "prompt", "label": "Prompt", "type": "text", "required": True, "default": "Analyze the codebase for regressions."},
            {"key": "agentId", "label": "Agent ID", "type": "agent_select", "required": True, "default": "supervisor"},
            {"key": "maxTurns", "label": "Max turns", "type": "number", "required": True, "default": 10},
            {"key": "timeoutSeconds", "label": "Timeout seconds", "type": "number", "required": True, "default": 300},
        ],
    },
]

NODE_BY_TYPE = {node["type"]: node for node in NODE_TYPES}


def default_config(node_type: str) -> dict[str, Any]:
    node = NODE_BY_TYPE[node_type]
    return {field["key"]: field.get("default") for field in node["configSchema"]}


def list_node_types() -> list[dict[str, Any]]:
    return NODE_TYPES
